### ISSUE TITLE
Help with the conversion of Dependency Check generated reports to CycloneDX bom

### ISSUE THREAD

**Issue by aejazuddinam** [CycloneDX/cyclonedx-node-module#157]
Hi Team,

Im working on end to end declarative pipeline involving DC and DT, so need inputs from the community as after the DC report (xml) is generated, how to convert it to cyclonedx bom, or directly upload dependency-check-report.xml to DT.

**Comment by stevespringett** [comment]
To my knowledge, Dependency-Check does not support output to CycloneDX and even if it did, it would be missing a lot of information typically present in a CycloneDX SBOM.

Dependency-Track does not support consumption of Dependency-Check reports - only CycloneDX SBOMs.

**Comment by aejazuddinam** [comment]
Thanks Steve. 
So this means we cannot integrate both DC and DT in a single flow pipeline passing one input to another anytime?

Both should be created independent to each other.

**Comment by stevespringett** [comment]
That is correct. Older versions of DT supported DC XML reports directly, as most orgs had not yet adopted CycloneDX as it was relatively new at the time. There were a lot of issues with support for DC as the goals of the two projects are very different. IMO, I would try to produce CycloneDX natively in the build rather than trying to get DC to output CycloneDX.

**Comment by jkowalleck** [comment]
question solve. 
feel free to create new issue or add further comments, if you feel something is unclear.
