### ISSUE TITLE
[BOWER] Bower support

### ISSUE THREAD

**Issue by hanstdam** [CycloneDX/cyclonedx-node-module#35]
First of all, thanks for a great package!

I'm working with a few legacy projects and would like to track the bower dependencies in these projects.

I would like to ask if the direction of this project would allow support for bower?

I understand that bower is not being recommended anymore and I would be happy to help implement this functionality, however I thought I'd ask before submitting a PR or creating a separate module. 

Thanks

**Comment by stevespringett** [comment]
I think it really depends on how 'intrusive' the bower support would be. If supporting it would introduce a lot of bower-specific code, then I think a dedicated cyclonedx bower module would be best. If it's simply a matter of adding a library or two in order to parse bower.json, then perhaps we can include support for it in this module.

Also note, https://github.com/heremaps/oss-review-toolkit supports Bower and can generate CycloneDX. I have not personally tried it, but it may be worth investigating before jumping in to create a PR for a legacy build system.

**Comment by prabhu** [comment]
Happy to consider bower support in my fork - https://github.com/AppThreat/cdxgen/ which already supports few other languages other than node.

**Comment by jkowalleck** [comment]
bower support NEEDS to be a new project.
like https://github.com/CycloneDX/cyclonedx-webpack-plugin

**Comment by jkowalleck** [comment]
will close the issue.
feel free to try and improve https://www.npmjs.com/package/cdx-bower-bom
