### ISSUE TITLE
yarn 3.6.1 lockfile issue

### ISSUE THREAD

**Issue by chrisbgithub** [CycloneDX/cyclonedx-node-module#353]
Hello,

im using yarn 3.6.1 and the yarn.lock looks a bit different from yarn 1.x.x. 

i got the following Error 

`Unknown token: { line: 3, col: 2, type: 'INVALID', value: undefined } 3:2 in lockfile`

The error comes from the Module synp. Synp cant deal with the Lockfile.

ty

**Comment by jkowalleck** [comment]
This project used to be a tool-set and a library to work and generate [CycloneDX](https://cyclonedx.org/) Software Bill-of-Materials (SBOM) from npm and yarn based projects.
Since version 4.0, this was all split to individual projects, and this project changed to a bare meta-package.

this means: the described feature is no longer part of this project.
