### ISSUE TITLE
using -a option loses data from attached bom

### ISSUE THREAD

**Issue by richardzaat** [CycloneDX/cyclonedx-node-module#50]
We have a .net and npm project. When first analyzing the .net application with dotnet-cyclonedx a bom.xml is generated. If I want to use -a to combine the results from cyclonedx-bom and the dotnet-cyclonedx, it seems it removes every other .net package found from the combined list.
In the combined output I see all the npm packages, and only half of the package reported by dotnet. 

What I notice: dotnet reports for instance packages A B C D E F G H
then in the combined output I see A C E G

Or am I doing something wrong here?

**Comment by stevespringett** [comment]
I have not seen this. Will need to investigate.

**Comment by satifant** [comment]
I have the same issue with a cyclonedx-maven-plugin generated bom.xml added via -a.

I did some digging and might have some insights:
https://github.com/CycloneDX/cyclonedx-node-module/blob/a189aae8f6ac480defe5f082e923b0f59422db8c/bin/cyclonedx-bom#L75-L79

This loop does not behave as expected since the appendChild-Method actually **moves** the component-tag from the additionalDoc to doc and the additionalDocComponents gets shorter with every step. Thus with incremented index only every other element is added.
See:
https://github.com/xmldom/xmldom/blob/3db6ccf3f7ecbde73608490d71f96c727abdd69a/lib/dom.js#L503-L506

Hope this helps!

**Comment by coderpatros** [comment]
Thanks for the pick up @satifant

**Comment by coderpatros** [comment]
@richardzaat this should be fixed in the latest release.
